on:
  - push
  - pull_request

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack for Windows
        run: npm run pack:windows
      - name: Upload for Windows
        uses: actions/upload-artifact@v2
        with:
          name: ZpDIC for Shaleian (Windows)
          path: product/*.exe
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack for Mac
        run: npm run pack:mac
      - name: Upload for Mac
        uses: actions/upload-artifact@v2
        with:
          name: ZpDIC for Shaleian (Mac)
          path: product/*.dmg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack for Linux
        run: npm run pack:linux
      - name: Tar files
        run: tar -cvf "ZpDIC for Shaleian (Linux).tar" product/*.AppImage
      - name: Upload for Linux
        uses: actions/upload-artifact@v2
        with:
          name: "ZpDIC for Shaleian (Linux).tar"
          path: "ZpDIC for Shaleian (Linux).tar"
